### ISSUE TITLE
Revisit database interfaces

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#205]
Database layer needs to be revisited to allow alternate implementations to be easily written
- [ ] Consider removing/extending IPFS-aware blockstore in favor of a tenant-separated data store.
- [x] Consider adding an absraction for "data store".
- [x] Consider abstracting the knowledge of `encodedData` which is RecordsWrite specific away from message store.
- [x] Ensure AND syntax in filter is based on a common standard if not already
- [ ] Support multi-value/array indexes
- [x] Support range queries
- [ ] Explicit test suit to allow new implementation to be tested quickly with high confidence of compatibility.
- [ ] Would be nice if an alternate implementation (such as Mongo) is implemented to prove design and will be immediately useful to community and adoption.

**Comment by mistermoe** [comment]
@thehenrytsai thanks for collecting these and dumping them into 1 issue! they've all been mentioned in several different places over the course of a few months, so it's nice to be able to see them all listed in 1 place. much of this is sort of intertwined with what we end up doing for #198 

> 1. Consider removing/extending IPFS-aware blockstore in favor of a tenant-separated data store.

I'm going to provide some context as to why `BlockstoreLevel` is a part of `MessageStoreLevel` so that we can figure out whether it's something we want to remove.

one of @csuwildcat 's goals was to make it such that records could contain an arbitrary amount of data of any format. so, a record should be able to contain a small json object as data all the way to a 4gb blu-ray. Orthogonally, his first stab at implementing a DWN used a full IPFS node as the underlying datastore. 

We quickly realized that running a full ipfs node wasn't going to be possible in all the runtimes/environments that DWNs are expected to run in, so i came up with the `MessageStore` abstraction. I then leaned in on LevelDB's abstraction and existing ability to run in the browser and node environments to write `MessageStoreLevel` with the goal of shipping a single `MessageStore` implementation that worked in both the browser and node without having to think much about it. 

In order to keep the benefits of IPFS (specifically how it breaks large files down into chunks and stores them + a root CID that can be used to traverse the entire DAG to rebuild the original file) without using the entirety of IPFS, i decided to use _just_ the chunking mechanism specifically for `encodedData` to set us up to be able to handle large files. 

Great... but that didn't solve the entire problem because DWN messages are ingested as JSON objects e.g.

```json
{
    "recordId": "bafyreic73ua2wakx6eh3flr7nzssi2whawvxemyalsikj5db2wsitl3fzq",
    "descriptor": {
        "recipient": "did:key:z6MkqkntQsQZEvjKYXn6py1PePmwgGMRtBLHoZ4P33Vg7pkA",
        "method": "RecordsWrite",
        "protocol": "chat",
        "schema": "chat/thread",
        "dataCid": "bafybeib2ox5uujhuvkjfrzelwpc77awtzyzh4yute6q7zhic3jviqlzriu",
        "dateCreated": "2023-01-19T23:55:06.505106",
        "dateModified": "2023-01-19T23:55:06.505106",
        "dataFormat": "application/json"
    },
    "authorization": {
        "payload": "eyJ0YXJnZXQiOiJkaWQ6a2V5Ono2TWtxa250UXNRWkV2aktZWG42cHkxUGVQbXdnR01SdEJMSG9aNFAzM1ZnN3BrQSIsInJlY29yZElkIjoiYmFmeXJlaWM3M3VhMndha3g2ZWgzZmxyN256c3NpMndoYXd2eGVteWFsc2lrajVkYjJ3c2l0bDNmenEiLCJkZXNjcmlwdG9yQ2lkIjoiYmFmeXJlaWRwemUydmJ6dTJ1Z3Rob25zYmx5ZHUyNG1ncHViZXJ5aDY1ZXV5a3czbnRhcG1sbXpnbHkiLCJjb250ZXh0SWQiOiJiYWZ5cmVpYzczdWEyd2FreDZlaDNmbHI3bnpzc2kyd2hhd3Z4ZW15YWxzaWtqNWRiMndzaXRsM2Z6cSJ9",
        "signatures": [
            {
                "protected": "eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDprZXk6ejZNa2hQaXlZMTRGenJGc0pZdzJ1WGdER1VndXNCYmVHVnROTFBSalFwNnhTbTNmI3o2TWtoUGl5WTE0RnpyRnNKWXcydVhnREdVZ3VzQmJlR1Z0TkxQUmpRcDZ4U20zZiJ9",
                "signature": "LTy5ymZmFp5ngXLIZb_QyG0VNwo8eSGOk_Iybewl0FOCcBUcOTnU1ExdbjxTGHMdjb6ngouSoQGcMtHkd1hADQ"
            }
        ]
    },
    "encodedData": "OVRLYnFqVFl2NQ",
    "contextId": "bafyreic73ua2wakx6eh3flr7nzssi2whawvxemyalsikj5db2wsitl3fzq"
}
```

we can't reasonably expect a 4gb bluray to be base64url encoded and jammed into a json object. In order to fully support arbitrary amounts of data within a record, we need to explore how the data itself can be _streamed_ in alongside the message instead of _inside_.

so, we're at a crossroads here:
1. if we intend to support records containing arbitrary amounts of data, then keeping the blockstore around seems helpful because we can stream chunks in and store chunks. There are other orthogonal kinks we'd need to talk through that change the model a bit
2. if we dont intend to support arbitrary amounts of data, then getting rid of `BlockStore` gets much easier

would be curious to hear more about what you have in mind for (2) and (3) as both seem relevant here.

**Comment by csuwildcat** [comment]
We must support large binary, else the datastore becomes extremely limited, excluding a larger percentage of apps/use cases.

**Comment by mistermoe** [comment]
@csuwildcat conversation around how to do that is happening in #198

**Comment by thehenrytsai** [comment]
@mistermoe thanks! The context on `MessageStore` and `Blockstore` is super useful and insightful! Totally makes sense given the browser constraints, stands true even today.

> (2) Consider adding an abstraction for data store

I am referring to the store that stores the binary blobs if it wasn't clear, as we already have an abstraction of the higher layer `MessageStore` which is great. This consideration is driven by the desire to decouple from directly depending on IPFS's `Blockstore` interface due to our need to add tenant and record reference management on top. The problem with depending on `Blockstore` directly for me, is that it forces data reference management to be based on IPFS "pinning", which I agree could be more optimum in storage usage, but can also be harder to get right with concurrency scenarios. Maybe a dumber implementation is fine where binary data is scoped to each tenant, which means duplication of same data across tenants, but also means less garbage management, it just seems risky to mingle data across tenants in general; cloud backup services I use seem to prefer such simplistic approach also, even within one tenant (same photo in two folders are uploaded twice, so dumb). With a tenant aware datastore abstraction, it is entirely up to the implementer to decide how the data store is done, it's fine if we want to add on tenant/record management on top of IPFS's `Blockstore` as the underlying implementation, but it's also fine if we want to ditch it in favor of say bittorrent style chunking or AWS S3. I am not looking for anything complex for the interface, just so that `Blockstore` constraints/requirements doesn't bleed into the layer above. Perhaps (without too much thinking):

```javascript
write(tenant, messageId, dataStream)
```

I see the abstraction more of a useful separation of concern from engineering standpoint, even if it's just for the purpose of subdividing the `MessageStore` component as a whole, but maybe it is okay in the end to not have this abstraction and say: well if you want to use level implementation of the `MessageStore`, binary data is by design stored as IPFS blocks, it's implementation detail.

> (3) Consider abstracting the knowledge of `encodedData`

This one is probably more agreeable. It is a bit odd today that the datastore layer manipulates the message to get the CID to index and data to store, it's probably nicer if message store is dumber (though I agree it's already quite dumb, which is good!) and is given the binary data explicitly (in stream form as we discussed), so it has minimal knowledge about the message. Perhaps (also without much thinking):

```javascript
write(tenant, message, indexes, dataStream)
```

Pretty sure I naively oversimplified the problem at hand, but this's my general line of thinking.

**Comment by nearlyjuly** [comment]
Would it be feasible to have a basic dwn with some way to 'add on' a db depending on the implementation? For example a basic dwn within a wallet or small app, and then a standalone dwn that is hosted (locally or remotely) for heavy duty storage and use? There are already ecosystems around each db and hosting anyway, and facilitating a way to extend a dwn to plug into them would smooth integration I think. I was looking at the dwn-aggregator repo yesterday and something like that could perhaps be pared down a lot using browser apis and a 'lite' dwn (as in no need for the dwn-sdk, the messages can be created according to the specification using what's already available).

**Comment by mistermoe** [comment]
@thehenrytsai i'm totally in favor of an abstraction that is tenant aware. Also totally on board with with data duplication across tenants.

 Irrespective to that, aside from the `MessageStore` interface using `CID` as IDs, i don't think that there's anything _forcing_ a `MessageStore` implementer to think about IPFS pinning or `Blockstore` at all. That is specific to `MessageStoreLevel`. for example, `MessageStoreSqlite` could choose to ignore chunking entirely if it wants. Are you referring to `MessageStoreLevel` specifically?

my follow-up question for you is: how are you envisioning `MessageStore` and `DataStore` interacting with one another?
1. Not at all. they're siblings. calling code stores message in `MessageStore` and then stores data in `DataStore`
2. `MessageStore` constructor accepts an instance of `DataStore` as an argument
3. None of the above and i've misunderstood

no opinions yet on how they interact with one another. instinctively lean towards option 1. Biggest elephant in the room for me still is how we deal with large amounts of data.

**Comment by mistermoe** [comment]
> Would it be feasible to have a basic dwn with some way to 'add on' a db depending on the implementation? For example a basic dwn within a wallet or small app, and then a standalone dwn that is hosted (locally or remotely) for heavy duty storage and use?

@nearlyjuly i think that's already feasible given that `MessageStore` is an interface. for wallet/small-app scenario, could just use `MessageStoreLevel`. For beefy hosted DWN (remote or loval), i'd imagine people would probably want a scalable DB backing it, in which case they'd probably implement a `MessageStore` that used dynamo or mongo or sql or something like that under the hood. 

> I was looking at the dwn-aggregator repo yesterday and something like that could perhaps be pared down a lot using browser apis and a 'lite' dwn (as in no need for the dwn-sdk, the messages can be created according to the specification using what's already available).

the intent of aggregator is for it to be used server-side only. 

> (as in no need for the dwn-sdk, the messages can be created according to the specification using what's already available).

does this mean removing `MessageStore` from the sdk and just keeping message creation in it?

definitely lmk if i'm misunderstanding your question.

**Comment by nearlyjuly** [comment]
@mistermoe thank you I understand (I think) that the problem is a large record that has been added to over time can be extremely large, as the smaller amounts of encoded data within each message are manageable. But trying to send a single message with all the encoded data at once is not, so it all points towards either a size limit for each message or an adjacent datastream. I've never quite understood the role of the local node, would that contain absolutely all data that's in all the other dwns? Or is it just a locally hosted dwn?

**Comment by thehenrytsai** [comment]
@mistermoe: Super glad that we agree on multiple fronts. 

> how are you envisioning MessageStore and DataStore interacting with one another?

I was thinking of option 2 purely because of where `DataStore` is created currently. But agree with you that option 1 is entirely rational and in some sense better because the two components can be decoupled further, thanks for the great call out! I haven't made up my mind either but not too opinionated right now, a competing reasoning for option 2 could be the desire for `MessageStore` to hide/encapsulate logic for atomicity of (message write + data write) operations.
