### ISSUE TITLE
Revisit `dateCreated`, `dateModified`, and `datePublished` format

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#230]
Currently it is expected to be ISO 8601 UTC format, revisit to see if we should change to a custom format of nanoseconds since unix epoch or some other format.

**Comment by dcrousso** [comment]
so i tried taking a stab at this by changing the JS representation to a `Temporal.Instant` and having the JSON be a stringified `BigInt` (e.g. `"1234567890123456789"` vs `"2009-02-13T23:31:30.123456789Z"`), but quickly ran into some issues.

the current architecture of having the `message` be both the argument to construct a `RecordsWrite`/`RecordsQuery`/`RecordsDelete` means that we're kinda constrained to only having JSON types in our JS API, which IMO feels pretty constrained and isnt allowing us to take advantage of all the powerful JS APIs at our fingertips (e.g. we'd have to convert the ISO string to a `Temporal.Instant` each time we wanted to do a `Tempora.Instant.compare` instead of being able to have the property be a `Temporal.Instant` from the getgo).  id suggest we consider an architecture that actually pulls apart (and repacks) the JSON so that we can be much more OOP about all of this, instead of having things basically just be wrappers around JSON.

putting all that aside tho, here are some of the benefits and drawbacks of using other formats

-----

#### ISO-8601
##### Pros
- standardized format for creation and parsing
- very human readable
- extremely well known and supported (at least with only milliseconds precision)
##### Cons
- more verbose with lots of repeated characters (e.g. `-`, `T`, `:`, `Z`, etc.)
- most things I can find only support up to milliseconds precision \(even the [official standards page](https://www.iso.org/iso-8601-date-and-time-format.html) only lists milliseconds\)
- stringifying a `Date` to JSON automatically uses this, but parsing from JSON will not, so would still need a transformer if we wanted to manipulate a `Date` instead of a raw string
- manipulation and comparison are not very easy and likely require transforming to a different form to be done efficiently (or at all)

#### `BigInt`
##### Pros
- fantastic JS API for creation, manipulation, comparison, stringification, etc.
- easy interop with `Temporal.Instant`
- very standardized and fully builtin
- timestamps are a super understood concept (at least with only seconds/milliseconds precision) and have lots of benefits over date strings
##### Cons
- technically i believe that JSON doesnt have a maximum number size, but at least in the browser anything over 53bits causes precision loss, so the only actually usable intermediate representation would be a number string (e.g. `1234567890123456789`), which is more portable and comparable (arguably) to other formats (e.g. `"2009-02-13T23:31:30.1233456789Z"`) but is harder to parse back into its original form (at least with JSON)
- not very human readable or immediately understood that "this represents a UNIX timestamp with nanoseconds precision"

#### `Temporal.Instant`
##### Pros
- fantastic JS API for creation, manipulation, comparison, stringification, etc.
- very standardized (tho still a bit WIP)
##### Cons
- not JSON compatible (i.e. will need an intermediate representation when sending outside of JS)
- not fully implemented in all environments (yet)

-----

i really do think we should be using JS APIs (e.g. `Temporal.Instant` or at least a `Date`) and timestamps (ideally numbers, but a stringified numbers would also not suck) in transport, but given the current architecture im not sure we can really have that :(

**Comment by duncanmak** [comment]
@thehenrytsai can this be closed now that #113 has been merged?

**Comment by thehenrytsai** [comment]
Unlikely to change unless affecting functionality, closing.
