### ISSUE TITLE
Add support for `EdDSA` and `ES256K` key types in the browser.

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/dwn-sdk-js#26]
JOSE doesn't support `EdDSA` or `ES256K` (aka `secp256k1`) in the browser. I went ahead and added automated headless browser testing against our browser bundles so that we can fish out issues like these programmatically. 

The tests that generate `EdDSA` keys are currently failing in the browser.

**Comment by cwarny** [comment]
Some of the browser tests are failing because `Buffer.toString(<encoding>)` in the browser does not support  `base64url` encoding, although it does support `base64`. I think this is because Babel polyfills using [this package](https://github.com/feross/buffer), which, as [this issue](https://github.com/feross/buffer/issues/309) points out, does not support `base64url`. Maybe it has to do with the fact that the last release of this package was Nov 22, 2020, and the Node.js support for the `base64url` encoding was [added](https://github.com/nodejs/node/commit/223494c548) in August 2021.
