### ISSUE TITLE
Validate entire message instead of parts of it

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/dwn-sdk-js#312]
[permissions-request](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/interfaces/protocols/messages/protocols-query.ts#L38), [protocols-configure](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/interfaces/protocols/messages/protocols-configure.ts#L33), and [protocols-query](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/interfaces/protocols/messages/protocols-query.ts#L38) all validate like so:

```ts
Message.validateJsonSchema({ descriptor, authorization: { } });
```

we should consider constructing the entire message and _then_ validating unless there's a reason not to. many other message classes already do this

**Comment by alanhkarp** [comment]
One system I built validated parts of the message as well as the whole message (which you have to do even if the message contains only previously validated parts).  The idea was that often many messages share the bulk of the content with only minor changes, and we could validate the reusable parts once.  After doing it that way, I didn't see much of an advantage.  Maybe that was because our messages weren't all that big and verification was fast.

**Comment by thehenrytsai** [comment]
Done.
