### ISSUE TITLE
Implement data deletion in message store

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#84]
Currently the message store does not have the ability to delete data referenced by the CollectionsWrite messages. The implementation needs to take into account that:

1. Records within the same tenant can reference the same block.
2. Records across multiple tenants can reference the same block.

**Comment by thehenrytsai** [comment]
@dcrousso, I just did a sanity test of writing a 100MB data blob, then deleting it again. And the datastore folder still has ~100MB after deletion.

Can you sanity verify and investigate and fix if true?

**Comment by thehenrytsai** [comment]
Hey @dcrousso I did the same sanity test with a 100MB data blob before closing this issue, the level folder still appears to be 100MB in size... can you sanity verify on your end to make sure I am not dreaming?

**Comment by dcrousso** [comment]
im pretty sure that's how `leveldb` works, as a sort of performance optimization to prevent having to read the entire DB, figure out what to get rid of, and then (re)write it all back to disk (i.e. a kinda sorta somewhat operation similar to defragmentation)

if you do a test where you

1. `put` 100MB
2. `delete` 100MB
3. call `level.prototype.open` (repeat)

you should see that most of the time you call `level.prototype.open` the size of the folder on disk will go down (im pretty sure this is because one of the places where (partial) compaction happens is during `open`)

if it's a _hard_ requirement that we delete the data on disk _immediately_ then we might be able to leverage `ClassicLevel.prototype.compactRange` (though we'd have to figure out what to provide for `start` and `end`) which should trigger a compaction (of the given range), but IMO since the actual `leveldb` API doesn't expose this then i feel it's probably OK (i.e. you'd need access to the machine to get the data, or to have found some bug in `leveldb`) and it might utterly _tank_ the overall performance of the `Dwn`

lmk what you want me to do :)

**Comment by thehenrytsai** [comment]
This is now done.
